version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "localstack-sam-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9473a034"
s3_prefix = "localstack-sam-example"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
